export type HaryanaAreaType = "urban" | "rural";
export type HaryanaBuyerType = "male" | "female" | "joint_male_female";

/**
 * Standard sale/conveyance planning rates used for Haryana residential property.
 *
 * Haryana Revenue publishes a 5% base conveyance rate, with an additional urban
 * transfer duty and a 2% remission when the conveyance is in favour of a woman.
 * The joint male/female rates are the commonly published Haryana planning rates;
 * the final demand generated by HARIS/e-GRAS remains controlling.
 */
export const HARYANA_STAMP_DUTY_RATES: Record<
  HaryanaAreaType,
  Record<HaryanaBuyerType, number>
> = {
  urban: {
    male: 0.07,
    female: 0.05,
    joint_male_female: 0.06,
  },
  rural: {
    male: 0.05,
    female: 0.03,
    joint_male_female: 0.04,
  },
};

export const HARYANA_STAMP_DUTY_METADATA = {
  lastVerified: "2026-09-11",
  registrationFeeCap: 50_000,
  ordinaryConveyanceOnly: true,
} as const;

/**
 * Haryana registration fee schedule for ordinary property documents.
 * The current state position is slab-based and capped at Rs 50,000.
 */
export function getHaryanaRegistrationFee(assessableValue: number): number {
  const value = Math.max(0, Math.round(assessableValue));
  if (value === 0) return 0;
  if (value <= 50_000) return 100;
  if (value <= 100_000) return 500;
  if (value <= 500_000) return 1_000;
  if (value <= 1_000_000) return 5_000;
  if (value <= 2_000_000) return 10_000;
  if (value <= 2_500_000) return 12_500;
  if (value <= 3_000_000) return 15_000;
  if (value <= 4_000_000) return 20_000;
  if (value <= 5_000_000) return 25_000;
  if (value <= 6_000_000) return 30_000;
  if (value <= 7_000_000) return 35_000;
  if (value <= 8_000_000) return 40_000;
  if (value <= 9_000_000) return 45_000;
  return HARYANA_STAMP_DUTY_METADATA.registrationFeeCap;
}

export type HaryanaPurchaseChargeInput = {
  agreementValue: number;
  collectorRateValue?: number;
  areaType: HaryanaAreaType;
  buyerType: HaryanaBuyerType;
};

export type HaryanaPurchaseChargeResult = {
  assessableValue: number;
  stampDutyRate: number;
  stampDuty: number;
  registrationFee: number;
  totalBasicGovernmentCharges: number;
  collectorRateProvided: boolean;
};

/**
 * Planning estimate for an ordinary Haryana sale/conveyance deed.
 *
 * HARIS normally checks the deed consideration against the applicable Collector
 * rate. For a consumer-facing estimate we therefore use the higher entered value.
 * A party may seek statutory determination under section 47-A; special deeds and
 * exemptions must not be run through this ordinary-sale formula.
 */
export function calculateHaryanaPurchaseCharges({
  agreementValue,
  collectorRateValue = 0,
  areaType,
  buyerType,
}: HaryanaPurchaseChargeInput): HaryanaPurchaseChargeResult {
  const safeAgreementValue = Math.max(0, Number(agreementValue) || 0);
  const safeCollectorRateValue = Math.max(0, Number(collectorRateValue) || 0);
  const assessableValue = Math.max(safeAgreementValue, safeCollectorRateValue);
  const stampDutyRate = HARYANA_STAMP_DUTY_RATES[areaType][buyerType];
  const stampDuty = Math.round(assessableValue * stampDutyRate);
  const registrationFee = getHaryanaRegistrationFee(assessableValue);

  return {
    assessableValue,
    stampDutyRate,
    stampDuty,
    registrationFee,
    totalBasicGovernmentCharges: stampDuty + registrationFee,
    collectorRateProvided: safeCollectorRateValue > 0,
  };
}
