import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, CheckCircle2, MessageCircle, Phone, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { EnquiryForm } from "@/components/site/EnquiryForm";
import { CONTACT, LOAN_DISCLAIMER } from "@/data/site";
import { trackContact } from "@/lib/analytics";
import { SITE_ORIGIN } from "@/lib/seo";

const PAGE_PATH = "/jms-the-majestic-manesar";
const canonical = `${SITE_ORIGIN}${PAGE_PATH}`;
const title = "JMS The Majestic Manesar | 3 BHK Low-Rise Floors in Sector M9";
const description = "Explore JMS The Majestic in Sector M9, IMT Manesar: 3 BHK low-rise floors, indicative sizes, features, connectivity and buyer due diligence with Shubh Estate Brokers.";
const wa = `${CONTACT.whatsapp}?text=${encodeURIComponent("Hello, I am interested in JMS The Majestic, Sector M9, IMT Manesar. Please share current inventory, price sheet, floor plans and site visit availability.")}`;
const facts = [["Developer", "JMS Group"], ["Format", "Low-rise floors"], ["Configuration", "3 BHK"], ["Indicative size", "150–179 sq yd*"], ["Location", "Sector M9, IMT Manesar"], ["RERA reference", "Verify live HRERA record*"]] as const;
const features = ["3 bedrooms and 3 bathrooms*", "Puja room, lounge and private bar area*", "Basement office and additional lounge*", "Landscaped terrace areas and balconies*", "Modular kitchen with utility area*", "Private elevator access*", "Air-conditioned interiors*", "Stilt-level parking and surveillance*"] as const;
const amenities = ["Pedestrian areas*", "Swimming pool*", "Jogging track*", "Yoga terrace*", "Gymnasium*", "Indoor games*", "Retail / mall facility*", "Community open spaces*"] as const;
const faqs = [["What is the location of JMS The Majestic?", "Available project material places it in Sector M9, IMT Manesar, Gurugram. Confirm the exact site pin before visiting."], ["What configuration and size are shown?", "The accessible lead page shows 3 BHK low-rise floors of approximately 150–179 square yards. Confirm the approved area basis and available variants."], ["What is the price?", "A reference page displays ₹1.30 crore onwards. This is indicative only; obtain a current written cost sheet before booking."], ["Can Shubh Estate Brokers assist with finance and documents?", "Yes. We coordinate project evaluation, price assessment, lender discussions, title/document review, site visits and transaction steps. Loan approval remains subject to the lender."]] as const;

export const Route = createFileRoute("/jms-the-majestic-manesar")({
  head: () => ({ meta: [
    { title }, { name: "description", content: description }, { name: "robots", content: "index,follow,max-image-preview:large" },
    { property: "og:title", content: title }, { property: "og:description", content: description }, { property: "og:type", content: "website" }, { property: "og:url", content: canonical },
    { name: "twitter:card", content: "summary_large_image" }
  ], links: [{ rel: "canonical", href: canonical }], scripts: [{ type: "application/ld+json", children: JSON.stringify({
    "@context": "https://schema.org", "@graph": [
      { "@type": "WebPage", name: title, url: canonical, description },
      { "@type": "RealEstateAgent", name: CONTACT.name, url: SITE_ORIGIN, telephone: "+919911050561", address: { "@type": "PostalAddress", streetAddress: "15th Floor, Ocus Quantum Mall, Sector 51", addressLocality: "Gurugram", addressRegion: "Haryana", postalCode: "122003", addressCountry: "IN" } },
      { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: SITE_ORIGIN }, { "@type": "ListItem", position: 2, name: "Projects", item: `${SITE_ORIGIN}/projects` }, { "@type": "ListItem", position: 3, name: "JMS The Majestic Manesar", item: canonical }] },
      { "@type": "FAQPage", mainEntity: faqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) }
    ]
  }) }] }),
  component: Page,
});

function Page() {
  return <main className="overflow-hidden bg-background">
    <section className="surface-navy text-white"><div className="container-page grid min-h-[650px] items-center gap-10 py-16 lg:grid-cols-[1.1fr_.9fr]">
      <div><nav aria-label="Breadcrumb" className="text-xs text-white/60"><Link to="/">Home</Link><span className="px-2">/</span><Link to="/projects">Projects</Link><span className="px-2">/</span><span>Manesar</span></nav><Badge className="mt-7 border-gold/35 bg-gold/10 text-gold hover:bg-gold/10">Sector M9 · IMT Manesar · Gurugram</Badge><p className="mt-6 text-xs font-semibold uppercase tracking-[.25em] text-gold">JMS Group · Low-rise residential floors</p><h1 className="mt-4 max-w-3xl font-display text-4xl leading-tight sm:text-6xl">JMS The Majestic Manesar</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-white/70">A 3 BHK low-rise floor opportunity in Sector M9, presented with clear price context, due-diligence questions and practical buying assistance.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="xl" variant="gold"><a href="#enquire">Enquire now <ArrowRight /></a></Button><Button asChild size="xl" variant="goldOutline"><a href={wa} target="_blank" rel="noreferrer" onClick={() => trackContact("whatsapp", "jms_majestic_hero")}>WhatsApp <MessageCircle /></a></Button></div></div>
      <div className="rounded-3xl border border-white/15 bg-white/5 p-6"><p className="eyebrow">Project snapshot</p><dl className="mt-5 grid gap-3 sm:grid-cols-2">{facts.map(([label,value]) => <div key={label} className="rounded-2xl border border-white/10 p-4"><dt className="text-xs text-white/55">{label}</dt><dd className="mt-2 font-display text-lg">{value}</dd></div>)}</dl></div>
    </div></section>
    <section className="container-page py-14 sm:py-20"><div className="grid gap-10 lg:grid-cols-[1.2fr_.8fr]"><div><p className="eyebrow">Project overview</p><h2 className="mt-3 font-display text-3xl text-navy sm:text-4xl">Low-rise living near Manesar’s employment corridors</h2><p className="mt-5 leading-8 text-muted-foreground">The accessible project material describes JMS The Majestic as a low-rise residential development in Sector M9, IMT Manesar, with 3 BHK homes in approximately 150–179 square yards. Price, availability, specifications, approvals, timelines and amenity delivery should be confirmed in writing before booking.</p><p className="mt-5 text-sm text-muted-foreground">Shubh Estate Brokers is an independent property advisory and brokerage business, not the developer.</p></div><aside className="rounded-3xl border border-gold/25 bg-gold/5 p-7"><ShieldCheck className="size-7 text-gold" /><h2 className="mt-4 font-display text-2xl text-navy">Banking-grade property review</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">Shubh Estate Brokers provides practical property-buying assistance in Gurugram, including project evaluation, price assessment, home-loan guidance, title and document due diligence, site visits and transaction coordination.</p><p className="mt-4 text-sm font-medium text-navy">Up to 90% Home Loan Available, subject to borrower eligibility, lender policy and property documentation.</p></aside></div></section>
    <section className="border-y border-border bg-secondary/25 py-14 sm:py-20"><div className="container-page"><p className="eyebrow">Home features</p><h2 className="mt-3 font-display text-3xl text-navy">Features to verify against the current specification sheet</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{features.map(item => <div key={item} className="rounded-2xl border border-border bg-card p-5"><CheckCircle2 className="size-5 text-gold" /><p className="mt-4 text-sm leading-6">{item}</p></div>)}</div></div></section>
    <section className="container-page py-14 sm:py-20"><p className="eyebrow">Lifestyle facilities</p><h2 className="mt-3 font-display text-3xl text-navy">A community layer beyond the individual floor</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{amenities.map(item => <div key={item} className="rounded-2xl bg-muted p-5 text-sm">{item}</div>)}</div></section>
    <section className="surface-navy py-14 text-white sm:py-20"><div className="container-page grid gap-10 lg:grid-cols-2"><div><p className="eyebrow">Connectivity</p><h2 className="mt-3 font-display text-3xl sm:text-4xl">Manesar access, with route claims kept qualified</h2><p className="mt-5 leading-7 text-white/65">Reference material mentions NH-48, KMP Expressway, Dwarka Expressway, Gurugram–Rewari–Pataudi Highway and nearby industrial destinations. Exact distances, travel times, metro status and freight-corridor claims require live route and authority verification.</p></div><div className="overflow-hidden rounded-2xl border border-white/10"><table className="w-full text-left text-sm"><tbody>{[["NH-48","Regional Delhi–Gurugram access"],["KMP Expressway","Regional connectivity"],["Dwarka Expressway","Route referenced in source material"],["Industrial hubs","Honda and Maruti references require distance confirmation"],["Airport / metro","Time and proposed/upcoming status require confirmation"]].map(([route,note]) => <tr key={route} className="border-b border-white/10 last:border-0"><td className="p-4 font-medium">{route}</td><td className="p-4 text-white/60">{note}</td></tr>)}</tbody></table></div></div></section>
    <section className="container-page py-14 sm:py-20"><p className="eyebrow">Price guidance</p><h2 className="mt-3 font-display text-3xl text-navy">Use the entry price as a starting question, not a promise</h2><p className="mt-5 max-w-3xl leading-8 text-muted-foreground">One reference page displays ₹1.30 crore onwards and 150–179 square yards. Confirm the exact unit, area basis, floor, facing, parking, PLC, EDC/IDC, taxes, maintenance, payment plan and possession terms with the authorised sales team.</p><div className="mt-6 rounded-2xl border border-border bg-card p-6 text-sm text-muted-foreground">{LOAN_DISCLAIMER}</div></section>
    <section className="border-y border-border bg-secondary/25 py-14 sm:py-20"><div className="container-page grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Buyer questions</p><h2 className="mt-3 font-display text-3xl text-navy">JMS The Majestic FAQ</h2></div><div className="space-y-3">{faqs.map(([q,a]) => <details key={q} className="rounded-2xl border border-border bg-card p-5"><summary className="cursor-pointer font-display text-lg text-navy">{q}</summary><p className="mt-3 text-sm leading-7 text-muted-foreground">{a}</p></details>)}</div></div></section>
    <section id="enquire" className="container-page scroll-mt-24 py-14 sm:py-20"><div className="grid gap-10 lg:grid-cols-[1fr_.85fr]"><div><p className="eyebrow">Private enquiry</p><h2 className="mt-3 font-display text-4xl text-navy">Request current inventory or a site visit</h2><p className="mt-5 leading-7 text-muted-foreground">Share your preferred configuration, budget and buying purpose. We will help compare the available unit against documentation, financing and total-cost considerations.</p><div className="mt-7 flex flex-wrap gap-3"><Button asChild variant="gold"><a href={wa} target="_blank" rel="noreferrer" onClick={() => trackContact("whatsapp", "jms_majestic_enquiry")}>WhatsApp <MessageCircle /></a></Button><Button asChild variant="navy"><a href={CONTACT.phoneHref} onClick={() => trackContact("phone", "jms_majestic_enquiry")}>Call {CONTACT.phone} <Phone /></a></Button></div></div><div className="rounded-3xl border border-border bg-card p-7 shadow-sm"><EnquiryForm interest="JMS The Majestic Manesar" compact includeRequirements /></div></div></section>
    <section className="container-page pb-16 text-xs leading-6 text-muted-foreground"><p>Prices, availability, specifications and timelines are subject to change and should be confirmed with the developer or authorised sales team. Reference-site images and text have not been reused.</p></section>
  </main>;
}
